$schema: https://taskfile.dev/schema.json

version: "3"

tasks:
  install:
    run: once
    cmds:
      - task: install:npm

  build:
    run: once
    cmds:
      - task: build:cargo
      - task: build:npm

  test:
    run: once
    cmds:
      - >
        rm -rf coverage/*
      - task: test:cargo
      - task: test:npm
      - >
        grcov
        --binary-path target/debug/
        --output-path coverage/lcov.info
        coverage/*.profraw

  install:npm:
    run: once
    sources:
      - package-lock.json
    generates:
      - node_modules/**
    cmds:
      - npm install

  build:cargo:
    run: once
    cmds:
      - task: build:cargo:jns42-core
      - task: build:cargo:jns42-generator
      - task: build:cargo:jns42-tester

  build:npm:
    run: once
    cmds:
      - task: build:npm:jns42-core
      - task: build:npm:jns42-lib
      - task: build:npm:jns42-generator

  test:cargo:
    run: once
    env:
      CARGO_INCREMENTAL: "0"
      RUSTFLAGS: "--codegen instrument-coverage=all"
      LLVM_PROFILE_FILE: "{{.PWD}}/coverage/default_%m_%p.profraw"
    cmds:
      - cargo test --quiet

  test:npm:
    run: once
    deps:
      - build:npm
    env:
      NODE_V8_COVERAGE: "{{.PWD}}/coverage"
    cmds:
      - npm test

  build:cargo:jns42-core:
    run: once
    sources:
      - Cargo.lock
      - packages/cargo/jns42-core/src/**
    generates:
      - target/release/libjns42_core.*
      - target/wasm32-unknown-unknown/release/jns42_core.*
    cmds:
      - >
        cargo build
        --package jns42-core 
        --release
        --quiet
      - >
        cargo build
        --package jns42-core 
        --target wasm32-unknown-unknown
        --release
        --quiet
      - >
        wasm-tools component new
        --output target/wasm32-unknown-unknown/release/jns42_core.component.wasm
        target/wasm32-unknown-unknown/release/jns42_core.wasm

  build:cargo:jns42-generator:
    run: once
    sources:
      - Cargo.lock
      - packages/cargo/jns42-generator/src/**
    generates:
      - target/release/jns42-generator
    deps:
      - build:cargo:jns42-core
    cmds:
      - >
        cargo build
        --package jns42-generator 
        --release
        --quiet

  build:cargo:jns42-tester:
    run: once
    sources:
      - Cargo.lock
      - packages/cargo/jns42-tester/src/**
    generates:
      - target/release/jns42-tester
    deps:
      - build:cargo:jns42-core
    cmds:
      - >
        cargo build
        --package jns42-tester 
        --release
        --quiet

  build:npm:jns42-core:
    run: once
    sources:
      - package-lock.json
      - packages/npm/jns42-core/src/**
    generates:
      - packages/npm/jns42-core/dist/**
    deps:
      - install:npm
      - build:cargo:jns42-core
    cmds:
      - npm --workspace @jns42/core run generate

  build:npm:jns42-lib:
    run: once
    sources:
      - package-lock.json
      - packages/npm/jns42-lib/src/**
      - packages/npm/jns42-lib/tsconfig.json
    generates:
      - packages/npm/jns42-lib/transpiled/**
      - packages/npm/jns42-lib/typed/**
      - packages/npm/jns42-lib/bundled/**
      - packages/npm/jns42-lib/tsconfig.tsbuildinfo
    deps:
      - install:npm
    cmds:
      - npm --workspace @jns42/lib run tsc
      - npm --workspace @jns42/lib run bundle

  build:npm:jns42-generator:
    run: once
    sources:
      - package-lock.json
      - packages/npm/jns42-generator/src/**
      - packages/npm/jns42-generator/tsconfig.json
    generates:
      - packages/npm/jns42-generator/transpiled/**
      - packages/npm/jns42-generator/typed/**
      - packages/npm/jns42-generator/bundled/**
      - packages/npm/jns42-generator/tsconfig.tsbuildinfo
    deps:
      - install:npm
      - build:npm:jns42-core
      - build:npm:jns42-lib
    cmds:
      - npm --workspace @jns42/generator run tsc
      - npm --workspace @jns42/generator run bundle
