[package]
name = "jns42-core"
version = "0.1.3"
edition = "2024"
description = "Core of jns42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema"]
repository = "https://github.com/LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
im = "^15.1.0"
url = "^2.5.4"
serde = { version = "^1.0.219", features = ["derive"] }
serde_json = "^1.0.140"
serde_yaml = "^0.9.34"
once_cell = "^1.21.3"
quote = "^1.0.40"
regex = "^1.11.1"
urlencoding = "2.1.3"
itertools = "0.14.0"
semver = "1.0.26"
wit-bindgen = "0.43.0"

[dev-dependencies]
tokio = { version = "1.46.1", features = ["full"] }

[lib]
crate-type = ["rlib", "cdylib"]
