[package]
name = "jns42-generator"
version = "0.1.0"
edition = "2024"
description = "Generate structs and validators from json schema"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema", "generator"]
repository = "git@github.com:LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "^4.5.40", features = ["derive"] }
futures-util = "^0.3.31"
http-body-util = "^0.1.3"
im = "^15.1.0"
once_cell = "^1.21.3"
proc-macro2 = "^1.0.95"
quote = "^1.0.40"
regex = "^1.11.1"
rust-format = { version = "^0.3.4", features = ["token_stream"] }
serde = "^1.0.219"
serde_json = "^1.0.140"
serde_yaml = "^0.9.34"
toml = "^0.8.23"
url = "^2.5.4"
urlencoding = "^2.1.3"
jns42-core = { path = "../jns42-core" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "jns42-generator"
path = "src/main.rs"
