on:
  pull_request:

jobs:
  install-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.npm/
            ~/.cache/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: go-task/setup-task@v1
        with:
          version: "3.50"
      - uses: actions/setup-node@v4
        with:
          node-version: "26"
      - run: rustup default 1.97.0
      - run: task install check

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.npm/
            ~/.cache/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: go-task/setup-task@v1
        with:
          version: "3.50"
      - uses: actions/setup-node@v4
        with:
          node-version: "26"
      - run: rustup default 1.97.0
      - run: task build test
